
package service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileShareService", targetNamespace = "http://service/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface FileShareService {


    /**
     * 
     * @param filename
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String getFileOwner(
        @WebParam(name = "filename", partName = "filename")
        String filename);

    /**
     * 
     * @param searchQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String searchFiles(
        @WebParam(name = "searchQuery", partName = "searchQuery")
        String searchQuery);

    /**
     * 
     * @param filename
     * @param clientPort
     * @param clientAddress
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean unregisterFile(
        @WebParam(name = "filename", partName = "filename")
        String filename,
        @WebParam(name = "clientAddress", partName = "clientAddress")
        String clientAddress,
        @WebParam(name = "clientPort", partName = "clientPort")
        int clientPort);

    /**
     * 
     * @param filename
     * @param clientPort
     * @param clientAddress
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean registerFile(
        @WebParam(name = "filename", partName = "filename")
        String filename,
        @WebParam(name = "clientAddress", partName = "clientAddress")
        String clientAddress,
        @WebParam(name = "clientPort", partName = "clientPort")
        int clientPort);

}
