
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileShareService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/FileShareService/FileShareService?wsdl")
public class FileShareService_Service
    extends Service
{

    private final static URL FILESHARESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILESHARESERVICE_EXCEPTION;
    private final static QName FILESHARESERVICE_QNAME = new QName("http://service/", "FileShareService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/FileShareService/FileShareService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILESHARESERVICE_WSDL_LOCATION = url;
        FILESHARESERVICE_EXCEPTION = e;
    }

    public FileShareService_Service() {
        super(__getWsdlLocation(), FILESHARESERVICE_QNAME);
    }

    public FileShareService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILESHARESERVICE_QNAME, features);
    }

    public FileShareService_Service(URL wsdlLocation) {
        super(wsdlLocation, FILESHARESERVICE_QNAME);
    }

    public FileShareService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILESHARESERVICE_QNAME, features);
    }

    public FileShareService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileShareService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileShareService
     */
    @WebEndpoint(name = "FileShareServicePort")
    public FileShareService getFileShareServicePort() {
        return super.getPort(new QName("http://service/", "FileShareServicePort"), FileShareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileShareService
     */
    @WebEndpoint(name = "FileShareServicePort")
    public FileShareService getFileShareServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "FileShareServicePort"), FileShareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILESHARESERVICE_EXCEPTION!= null) {
            throw FILESHARESERVICE_EXCEPTION;
        }
        return FILESHARESERVICE_WSDL_LOCATION;
    }

}
