
/**
* FileShareHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Wednesday, July 2, 2025 2:08:06 AM EDT
*/


/**
 * FileShare interface defines the contract for the central registry server
 * in the P2P file sharing system. This interface allows clients to:
 * - Register files for sharing with other peers
 * - Unregister files when they're no longer available
 * - Search for files by name patterns
 * - Discover which peer owns a specific file for direct connection
 */
public final class FileShareHolder implements org.omg.CORBA.portable.Streamable
{
  public FileShare value = null;

  public FileShareHolder ()
  {
  }

  public FileShareHolder (FileShare initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FileShareHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FileShareHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FileShareHelper.type ();
  }

}
