
/**
* FileShareHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FileShare.idl
* Wednesday, July 2, 2025 2:08:06 AM EDT
*/


/**
 * FileShare interface defines the contract for the central registry server
 * in the P2P file sharing system. This interface allows clients to:
 * - Register files for sharing with other peers
 * - Unregister files when they're no longer available
 * - Search for files by name patterns
 * - Discover which peer owns a specific file for direct connection
 */
abstract public class FileShareHelper
{
  private static String  _id = "IDL:FileShare:1.0";

  public static void insert (org.omg.CORBA.Any a, FileShare that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FileShare extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (FileShareHelper.id (), "FileShare");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FileShare read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FileShareStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FileShare value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static FileShare narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileShare)
      return (FileShare)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FileShareStub stub = new _FileShareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static FileShare unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof FileShare)
      return (FileShare)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _FileShareStub stub = new _FileShareStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
